### ISSUE TITLE
Schedule initial training session on making paelographic observations

### ISSUE THREAD

**Issue by neelsmith** [HCMID/chant#1]
Can we work schedule a training session for making paelographic obsevations, together with the Chaucer group?

**Comment by neelsmith** [comment]
First week after fall break would be Oct. 25:  probably a good time, since the club is hosting a guest speaker the following week (Nov. 1).

**Comment by mikedunbar92** [comment]
The 25th works for me. I am free 3-4pm and after 5pm. 
Mike
